name: Docker Image CI
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build . --file Dockerfile --tag happy/flask-uwsgi:python3.7
      - name: Publish
        uses: zenato/docker-action@v1.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: happy/flask-uwsgi
          tag: python3.7
